# Assignment 3 - Question 3 : Hypothesis Testing Exercise on Buyers Ratio Dataset

## Problem Statement : Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

### We are going to conduct a Test of Independence using Chi-Square Test with contingency table.

### We need to check whether the proportion of male to female buyer in any of the resign is different or the same in all.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [2]:
data = pd.read_csv('C:/Users/LENOVO/Desktop/Assignment Data Science/3rd/BuyerRatio.csv')

In [3]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

# Declare Null and Alternate Hypothesis

### Null Hypothesis (Ho) : There is no association or dependency between the gender based buyer rations across regions
### Alternative Hypthosis (Ha) : There is a significant association or dependency between the gender based buyer rations across regions

### Level of significance (α) = 0.05

In [14]:
# Make diamensional array

obs = np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

## Applying Chi-Square Contingency Table to convert observed value into expected value

In [19]:
test_stat, p_value, dof, exp_val_array = stats.chi2_contingency(obs)

print(test_stat,"\n", p_value,"\n", dof,"\n", exp_val_array)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [20]:
p_value

0.6603094907091882

In [21]:
alpha = 0.05

if p_value <= alpha:
    print('We reject Null Hypothesis')
else:
    print('We fail to reject Null hypothesis')

We fail to reject Null hypothesis


# We fail to reject Null Hypothesis because of lack evidence. Therefore, there is no association or dependency between male-female buyers rations and are similar across regions.